stages:
  - test

#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - node_modules/
#    - .npm/

test:
  image: cypress/browsers:node18.12.0-chrome106-ff106
  stage: test
  script:
    - npm ci
    - npm start &
#    - npm run test
    - npx cypress run --browser firefox