import ComparisonProvider, { ComparisonContext } from '@/context/ComparisonParamProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import logo from 'public/enpal-logo.svg'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <ComparisonProvider>
          {children}
        </ComparisonProvider>
        <div id="banner">
          <Image id="enpal-logo" src={logo} alt="Enpal ." />
        </div>
      </body>
    </html>
  )
}
