name: firebase_deploy_onPush
on:
  push:
    branches:
      - xxx
  workflow_run:
     workflows:
       - unit and e2e tests
     types:
       - completed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOLAR_PROTOKOL }}'
          channelId: live
          projectId: solar-protokol
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
