name: cypress e2e tests
on: push
env:
  NODE_ENV: test
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - uses: actions/upload-artifact@v3
        with:
            name: cypress-snapshots
            path: cypress/snapshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
