#name: Cypress Tests
#env:
#  NODE_ENV: test
#on: push
#jobs:
#  cypress-run:
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Cypress run
#        uses: cypress-io/github-action@v6
#        with:
#          build: npm run build
#          start: npm start
#          browser: chrome
#          headed: true
#
name: unit and e2e tests
on: push
env:
  NODE_ENV: test
jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  test-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: unit test
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          headed: true
